# Generated by Django 4.2.3 on 2023-07-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Movie',
        ),
    ]
