# Generated by Django 4.2.3 on 2023-07-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='This is a title field', max_length=100),
        ),
    ]
